# -*- coding: utf-8 -*-
"""grafico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PB0HFa2crk-HVM2CnYdDDhz5HldUXCPS
"""



import pandas as p
import matplotlib.pyplot as plt

def gerar_scatter(x, y, title="Titulo", x_label="Eixo X", y_label="Eixo Y"):
  plt.title(title)
  plt.xlabel(x_label)
  plt.ylabel(y_label)
  plt.scatter(x, y)
  plt.show()

x = [1,2,3,4,5,6,7,8,9,10]
y = [1,2,3,4,5,6,7,8,9,10]

gerar_scatter(x, y, "Disperção das notas ao longo dos meses", "Meses", "Notas")

#def gerar_arquivo(nome _arquivo, eixoX, listaNomes, titulo, labelx, listY):
  #leitura = p.read_csv(nome_arquivo)
  #valoresX = leitura[eixoX]
  #colunasDeY = [leitura[colunaY] for
 #colunaY in listY]

 #plt.stackplot(valoresX,colunasDeY, label=listaNomes)

   #plt.title(titulo)
   #plt.xlabel(x_label)
   #plt.ylabel(y_label)
   #plt.show()

 #caminho=""